server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
        namespace: ${NACOS_NAMESPACE:public}
    gateway:
      discovery:
        locator:
          enabled: true    # 在网关中，启用服务发现
          lower-case-service-id: true # 服务名称转为小写

      routes: # 路由配置
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=X-User-Id
            - RemoveRequestHeader=X-User-Name
            - RemoveRequestHeader=X-User-Enabled
            - RemoveRequestHeader=X-User-Authorities
            - name: CustomRequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
        - id: user-service # 用户服务
          uri: lb://user-service # 服务地址 ， lb: 是Load Balancer的简写，表示使用负载均衡
          predicates:
            - Path=/api/user/**  # 匹配路径
          filters: # 网关过滤器
            - StripPrefix=1 # 去掉前缀
            - name: CustomRequestRateLimiter # 自定义的请求率限制器，注意：类名必须要是在这个name的后面加：GatewayFilterFactory
              args:
                redis-rate-limiter.replenishRate: 1    # 令牌桶填充速率（每秒生成10个令牌）
                redis-rate-limiter.burstCapacity: 2    # 令牌桶总容量（最多允许20个并发请求）
                key-resolver: "#{@ipAddressKeyResolver}" # 限流键解析器（基于IP）


        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true # 启动时加载规则
      scg: # 配置Sentinel的SCG
        fallback: # 降级处理
          mode: response # 降级处理方式 ，response：返回自定义的响应结果 ; redirect：重定向到指定的URL
          response-body: '{"code":429,"message":"请求过于频繁，请稍后再试！"}'
          response-status: 429
          content-type: application/json
      # 日志配置（便于排查问题）
#      log:
#        dir: ./logs/sentinel              # 日志目录
#        switch-pid: true                  # 日志文件名包含PID


  redis:
    host: localhost  # Redis服务器地址
    port: 6379       # Redis端口
    password: 123456
    database: 0      # 数据库索引
#  main:
#    web-application-type: reactive # 使用Reactive模式
#    allow-bean-definition-overriding: true # 允许覆盖bean的定义

jwt:
  secret: ${JWT_SECRET:jabari-tech-secret-key}
  private-key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSBXSp/tIkAvqgY5CnSSAobyxMbHrB3KSAwp3VxiSVNZX5I/BLvEALZrg2/MpxnZWAZ6PVQukuPucEQU3ltjrKy9gXHqeDykBiHPv17QReI19FKNb+1D90Cp+xTBl6L4mF7b2WDHgw4mNWdCv1ooKiGHWKQ23lwM67+h4/H8t9mmyGoE9iYN3VX0tjpC7Ak7ANZw5qKZiGR9Y/UyRuYYH86g+lTYYj37RbKdposAh6GQxBC3s+7eTJdAILeChyXsyX1im26p1urt2ttLAFHDODfYt+EKxlaUq3BNXwtiZfZozJr+O/5nKtSc3Jl/xFE66+p/OYMnLaaGQZAcKUtOSdAgMBAAECggEBAIah8LO5IsTrE/cVXHmgqvjAq8kiEV+NLfdMyxlrN7Be9ZEMtNIYD4Y/hv/Y9X334wq5ZZEkn46BzF4x7tm/A9lU62WGxSP612MN6YcxNYeTbVNMZuZc8YBV/yENA5gMOUCdstcpjzLnLX8SYcvJLazzuQW1TBHok551LEaS/0O4PPshX0kOrf/4ZzDTs+xiQOExGpOZ4K4xECblJFYlCgjQ8KynEuxmfVoGhbu2OLd/n7IfxrRWTWAfK5xu5AKVPiE976rzL0xhwavSKRCKmNKOY/Vtjuar9sRxE+I90Hh7oKuCCs097h0ToqF6Z9cgEIA1aK8ZvT36VILL963HYZECgYEA9KVCCenH1l353iAThdv9vPycF6gOG1M4yXaQQqoR1JSvkFa1DX5FBQ80LQEIQwZ5MIctICPy3EbRAtL0gY+ORMFYPSqfeOW+sTR0D+puJzVcq7oSwlgiuy05UcSm7Jm1pf0tRxzIxWVrIPd5I10/yDtMx+jkHHCjbxhOihNM9y8CgYEA28TP3SK3WyzF1L+WMCTGCBqOAYb5KzR2PDEfb0Me52fq+vJRNE4wxOORECFcbb5aX3sukMz0DUXYOztgCe7SxMg1VS4eksf2f5qMX9aCBTSQnQ4amba7AsaoZDKU081FTsiYBcQ8V+Fd1gGLxEBhBzJsQFnPySSr9WLHMTs9LfMCgYBdyUy7yCeYAobbpKhXVLK9VInyd7aQuyK1+QHszI3xVN7JErRt685B1kZGSnMEXuLuu6ONArsDvxI5Zu3dDU+ZBBXzvPdNvaWRAW7M+y4nUcmo+7hdULRf1UJ4Gk9zvKlqbNiCvoIpSmv7Q2PpLsJY3ILe0GVCkdvVpxfUzvleeQKBgFLQf2PdSSraXFInP/k0Ykt7djetHQfi5QsZl7bdnC+nQSz/UwpazJXlCy0A5UuVh4ijapC2KuE1iJ4Jac9UZ6gvqalHj83P/FtpaaxTsPs1K6mDPxLdgOsy4RGg3eRSXeOqQ18o63RSQIH8Yya4+9cycQhuz5YEc6gsaNNsd0lxAoGBALcf3AoT67PSe9ZS+S3I3SjAV637OXn5Qpo++5c3qF9wn+zCHc5gfdaCmRA+9qy1O35Z0pgtK63oGS43q7KU1vwBSAKbWY93bkEGkqZzRVdXPgE+nDT6XhZFjjXAqkycDOj57gJVsIYfagHFS+xb3ipC+mS3pCt9WGglNw1mZqBc
    -----END PRIVATE KEY-----
  expiration: ${JWT_EXPIRATION:86400} # 24小时
  token-header: Authorization
  token-prefix: Bearer

auth:
  excludePaths: # 无需登录校验的路径
    - /api/search/**
    - /api/auth/login
    - /api/auth/refresh
#    - /api/product/**
    - /v2/api-docs/**
    - /v3/api-docs/**
    - /swagger-resources/**
    - /swagger-ui/**
    - /webjars/**
    - /actuator/**


#开启控制台日志
logging:
    level:
      root: info
      org.springframework.cloud.gateway: debug
      org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: error
