server:
  port: 8081

feign:
  okhttp:
    enabled: true

jabari:
  sw:
    tit: '用户服务接口文档'
    desc: '用户服务接口Swagger文档'
    pack: 'tech.jabari.user.controller'
  db:
    database: user_db


  cloud:
    inetutils:
      preferred-networks: 192,10,172  # 指定优先使用的网段

    # nacos 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置Nacos注册中心地址（单机版）
        #        server-addr: 192.168.1.3:8848,192.168.1.3:8858,192.168.1.3:8868 # 配置Nacos注册中心地址（集群版）
        namespace: public # 命名空间，默认值： public；注意如果为其它值，需要手动在 Nacos里面创建命名空间，这里填：命名空间ID。
        group: DEFAULT_GROUP  # 服务分组，默认值： DEFAULT_GROUP，不需要手动创建，nacos会自动生成！
        metadata:
          nacos.weight: "1.0"












