server:
  port: 8081

spring:
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 关闭新版的PathPatternMatcher

  cloud:
    inetutils:
      preferred-networks: 192,10,172  # 指定优先使用的网段
    # nacos 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置Nacos注册中心地址（单机版）
#        server-addr: 192.168.1.3:8848,192.168.1.3:8858,192.168.1.3:8868 # 配置Nacos注册中心地址（集群版）
        namespace: public # 命名空间，默认值： public；注意如果为其它值，需要手动在 Nacos里面创建命名空间，这里填：命名空间ID。
        group: DEFAULT_GROUP  # 服务分组，默认值： DEFAULT_GROUP，不需要手动创建，nacos会自动生成！
        metadata:
          nacos.weight: "1.0"

    sentinel:
      transport:
          dashboard: localhost:8858
          port: 8719
      datasource:
        degrade-rule-ds: # 数据源名称（名称：可以自定义）
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-sentinel-degrade
            groupId: DEFAULT_GROUP
            rule-type: degrade



  #        weight: 20 # 服务权重，默认值： 1
  #      config:
#        server-addr: localhost:8848

  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#  sentinel:
#    enabled: true

# 日志配置 - 添加这部分来启用负载均衡日志
logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.netflix.ribbon: DEBUG
    com.netflix.loadbalancer: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    tech.jabari.user: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"